name: personal_ledger_mvp
description: "MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Page Move
  go_router:

  #Dependency Injection
  get_it:

  #State Management
  flutter_riverpod:
  riverpod_annotation:
  riverpod_generator:
  riverpod_lint:

  #REST API
  dio:
  retrofit:
  retrofit_generator:
  mockito:

  #REST Modeling
  freezed:
  json_annotation:
  json_serializable:
  dartz:
  equatable:

  #Debounce/Throttle
  easy_debounce:

  #Utility
  velocity_x:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: GmarketSansOTF
      fonts:
        - asset: asset/fonts/GmarketSansOTF/GmarketSansMedium.otf
          weight: 800
        - asset: asset/fonts/GmarketSansOTF/GmarketSansLight.otf
          weight: 600
        - asset: asset/fonts/GmarketSansOTF/GmarketSansLight.otf
          weight: 400